export const BIZSIM_CONFIG = {
  NAME: 'BizSim',
  VERSION: '1.1.1-dev',
  VAR_PATH: 'bizsim',
  FLOOR_NAMESPACE: {
    assetsKey: 'bizsim_assets',
    worldStateKey: 'bizsim_world_state',
  },
  LLM: {
    apiUrl: 'http://127.0.0.1:3423/v1',
    apiKey: 'sk-YNyHpwu69NOkHhJUafrn17oo40ch3SSBGXaZs8uB87bWdGAf',
    persistApiKey: true,
    model: '公益-Gcli-gemini-3-flash-preview',
    temperature: 0.6,
    maxTokens: 88888,
    timeoutMs: 120000,
    forceJsonResponse: true,
    customHeaders: '{}',
  },
  SIMULATION: {
    minTracks: 3,
    maxTracks: 10,
    trackPrefix: 'BG',
    historyLimit: 10,
    assetHistoryFloors: 10,
    worldHistoryFloors: 10,
    worldbookName: '',
    worldbookSelectedUids: '',
    useActiveWorldbooks: true,
    worldbookNames: '',
    worldbookEntrySelectors: '',
    worldbookEntryLimit: 12,
    useHistory: true,
    mode: 'balanced',
    includeFloorData: true,
    includeWorldState: true,
    bodyInjectionEnabled: false,
    retryCount: 2,
    repairOnParseError: true,
    autoSave: true,
    autoRunEnabled: false,
    autoRunOnlyAssistant: true,
    autoRunAssistantFloorInterval: 1,
    autoRunUseHistory: true,
    autoRunMinChars: 300,
    autoRunCooldownSec: 8,
    contentExtractTags: 'content,game',
    contentExcludeTags: 'details,UpdateVariable,background,tucao,reasoning,analysis,think,npc_action,recall,dm_box',
  },
  AUDIT: {
    cashToleranceWan: 1,
    enterpriseToleranceWan: 1,
    liquidationPenalty: {
      min: 0.3,
      max: 0.7,
    },
    loyaltyThreshold: 50,
  },
};

// 提示词块 ID 常量（用于模块化架构）
export const PROMPT_BLOCK_IDS = {
  CONSTRAINT_LAYER: 'constraint_layer',
  RULE_LAYER: 'rule_layer',
  EXECUTION_STEPS: 'execution_steps',
  HISTORY_FLOOR_INFO: 'history_floor_info',
  WORLDBOOK_CONTEXT: 'worldbook_context',
  HISTORICAL_ASSET_VARS: 'historical_asset_vars',
  HISTORICAL_WORLD_VARS: 'historical_world_vars',
  CURRENT_ASSET_CONTEXT: 'current_asset_context',
  CURRENT_WORLD_CONTEXT: 'current_world_context',
  OUTPUT_TEMPLATE: 'output_template',
};
