import {
  DEFAULT_BREAK_PROMPT,
  DEFAULT_CORE_PROMPT_BLOCK,
  DEFAULT_COMPOSE_PROMPT,
  DEFAULT_EMPIRE_AUDIT,
} from './defaultPrompts.js';

export const PROMPTS = {
  COMPOSE_PROMPT: DEFAULT_COMPOSE_PROMPT,
  BREAK_PROMPT: DEFAULT_BREAK_PROMPT,
  CORE_PROMPT_BLOCK: DEFAULT_CORE_PROMPT_BLOCK,
  EMPIRE_AUDIT: DEFAULT_EMPIRE_AUDIT,
};
